[package]
name = "py_bindings"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
autere_db = { path = "../autere_db" }
pyo3 = "0.22.3"
rust_decimal = { version = "1.36.0", features = [] }
